### ISSUE TITLE
its shit broke ching chong type shit

### ISSUE THREAD

**Issue by TravyDev** [timwhitez/Doge-Obf#1]
lgit worst code ive ever laid eyes on

**Comment by timwhitez** [comment]
just a practice project for me to learn static string obfuscation in Golang. If you think the code is bad, you can just ignore it instead of making a big fuss here; that is rude

**Comment by TravyDev** [comment]
https://github.com/user-attachments/assets/d9e10dc0-1281-4d32-bc15-a0c491192592

ok nig nog
